- name: dependencies
  color: '#5aa8fc'
  description: Pull requests that update a dependency file

- name: effort1:hours
  color: '#e38846'

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description

- name: dependencies
  color: '111111'
  description: A very inspiring description
