services:
  postgres-micromicro:
    image: postgres:16-bookworm
    container_name: postgres-micromicro
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${project_name_screaming_DATABASE_NAME}
      - POSTGRES_USER=${project_name_screaming_DATABASE_USER}
      - POSTGRES_PASSWORD=${project_name_screaming_DATABASE_PASSWORD}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${project_name_screaming_DATABASE_USER} -d ${project_name_screaming_DATABASE_NAME}'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '${project_name_screaming_DATABASE_PORT}:5432'
    volumes:
      - postgres-micromicro-data:/var/lib/postgresql/data
      - ../../../apps/micromicro/prisma/migrations:/prisma/migrations:ro
    restart: unless-stopped
    networks:
      - micromicro-db-net

volumes:
  postgres-micromicro-data:

networks:
  micromicro-db-net:
    name: micromicro-db-net
    driver: bridge
